In [1]:
import h5py
import numpy as np

In [2]:
simulation = "m12i"
sim_dir = "/Users/z5114326/Documents/simulations/"

proc_file = sim_dir + simulation + "/" + simulation + "_processed.hdf5"
proc_data = h5py.File(proc_file, "r")  # open processed data file

In [6]:
proc_data["it000"]["snapshots"].keys()

<KeysViewHDF5 ['snap020', 'snap023', 'snap026', 'snap029', 'snap033', 'snap037', 'snap041', 'snap046', 'snap052', 'snap059', 'snap067', 'snap077', 'snap088', 'snap102', 'snap120', 'snap142', 'snap172', 'snap214', 'snap277', 'snap294', 'snap312', 'snap332', 'snap356', 'snap382', 'snap412', 'snap446', 'snap486', 'snap534', 'snap590', 'snap591', 'snap592', 'snap593', 'snap594', 'snap595', 'snap596', 'snap597', 'snap598', 'snap599', 'snap600']>

In [7]:
proc_data["it000"]["snapshots"]["snap026"]["group_id"][()]

array([        0,    707419,    707419,   -707419,   -707419,   -707419,
         -707419,   -707419,  -1297671,  -1920378,  -1920378,  -1920378,
         1920378,  -1920378,   1920378,   1920378,  -1920378,  -1920378,
        -1920378,  -1920378,  -1920378,   1920378,  -1920378,  -1920378,
        -2422680,  -2422680,  -2422680,  -4414957,  -4414957,  -4414957,
         4414957,  -4414957,  -4414957,  -4414957,  -4414957,  -4414957,
        -4414957,  -4414957,   4414957,  -4414957,  -4414957,  -4414957,
        -4414957,  -4414957,  -4414957,  -4414957,  -4414957,  -4414957,
        -4414957,  -4414957,   4414957,  -4414957,  -4414957,  -4414957,
        -4414957,  -4414957,  -4414957,  -4414957,  -4414957,  -4906476,
        -4906476,  -5583343,  -5583343,  -5583343,  -6808839,  -8580896,
        -8580896,  -8580896,  -8580896,  -8580896,  -8580896,  -8580896,
        -8580896,  -8580896,  -8580896,  -8580896,  -8580896,  -8580896,
        -8580896,  -8580896,  -8580896,  -8580896, 

In [8]:
proc_data["it000"]["snapshots"]["snap077"]["halo.pos.xyz"][()]

array([[-1.        , -1.        , -1.        ],
       [-1.        , -1.        , -1.        ],
       [-1.        , -1.        , -1.        ],
       ...,
       [-0.24471196,  0.03241517, -0.12686722],
       [-0.01898297,  0.01069316,  0.29177427],
       [-0.22368136, -0.09216019, -0.24817684]])

In [13]:
ana_mask = proc_data["it000"]["source"]["analyse_flag"][()] == 1
snap_form = proc_data["it000"]["source"]["snap_zform"][()][ana_mask]
snap_form_pub = proc_data["it000"]["source"]["pubsnap_zform"][()][ana_mask]

match_count = 0
for snap, pubsnap in zip(snap_form, snap_form_pub):
    if snap == pubsnap:
        match_count += 1

match_count

372

In [17]:
proc_data["it000"]["snapshots"]["snap277"]["snap_part_idx"][()]

array([ 8368391, 67974345,  2469680, ...,  4711634,  1850400,   396626])

In [35]:
proc_data["it001"]["snapshots"]["snap600"]["l.xyz"]

<HDF5 dataset "l.xyz": shape (227, 3), type "<f8">

In [17]:
np.array(proc_data["it001"]["snapshots"]["snap046"]["group_id"])[13]

707419

In [18]:
np.array(proc_data["it001"]["snapshots"]["snap046"]["survived_accretion"])[13]

1

In [6]:
proc_data["it001"]["snapshots"]["snap600"].keys()

<KeysViewHDF5 ['accr_snap', 'analyse_flag', 'gc_id', 'group_id', 'mass', 'ptype']>

In [14]:
mask = np.where(np.array(proc_data["it001"]["snapshots"]["snap046"]["analyse_flag"]) == 0)
len(proc_data["it001"]["snapshots"]["snap046"]["analyse_flag"][mask])

13

In [8]:
proc_data.close()

In [11]:
import pandas as pd

public_snapshot_file = sim_dir + "snapshot_times_public.txt"
pub_data = pd.read_table(public_snapshot_file, comment="#", header=None, sep=r"\s+")
pub_data.columns = [
    "index",
    "scale_factor",
    "redshift",
    "time_Gyr",
    "lookback_time_Gyr",
    "time_width_Myr",
]
pub_snaps = np.array(pub_data["index"])


In [12]:
pub_snaps

array([ 20,  23,  26,  29,  33,  37,  41,  46,  52,  59,  67,  77,  88,
       102, 120, 142, 172, 214, 277, 294, 312, 332, 356, 382, 412, 446,
       486, 534, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600])

In [18]:
test = "False"
test_b = bool(test)

if test:
    t = 0
if not test:
    t = 1
else:
    t = 2

t

2