In [1]:
import h5py
import numpy as np

In [2]:
simulation = "m12i"
sim_dir = "/Users/z5114326/Documents/simulations/"

proc_file = sim_dir + simulation + "/" + simulation + "_processed.hdf5"
proc_data = h5py.File(proc_file, "r")  # open processed data file

In [9]:
ana_mask = proc_data["it000"]["source"]["analyse_flag"][()] == 1
snap_form = proc_data["it000"]["source"]["snap_zform"][()][ana_mask]
snap_form_pub = proc_data["it000"]["source"]["pubsnap_zform"][()][ana_mask]

match_count = 0
for snap, pubsnap in zip(snap_form, snap_form_pub):
    if snap == pubsnap:
        match_count += 1

match_count

372

In [7]:
proc_data["it000"]["snapshots"]["snap214"]["acc_snap"][()]

array([ -1,  -1,  -1, ..., 510, 510, 554])

In [8]:
proc_data["it000"]["snapshots"]["snap600"]["l.xyz"][1]

array([1550.44483885, 2553.73706274, -727.46643373])

In [17]:
np.array(proc_data["it001"]["snapshots"]["snap046"]["group_id"])[13]

707419

In [18]:
np.array(proc_data["it001"]["snapshots"]["snap046"]["survived_accretion"])[13]

1

In [6]:
proc_data["it001"]["snapshots"]["snap600"].keys()

<KeysViewHDF5 ['accr_snap', 'analyse_flag', 'gc_id', 'group_id', 'mass', 'ptype']>

In [14]:
mask = np.where(np.array(proc_data["it001"]["snapshots"]["snap046"]["analyse_flag"]) == 0)
len(proc_data["it001"]["snapshots"]["snap046"]["analyse_flag"][mask])

13

In [10]:
proc_data.close()

In [11]:
import pandas as pd

public_snapshot_file = sim_dir + "snapshot_times_public.txt"
pub_data = pd.read_table(public_snapshot_file, comment="#", header=None, sep=r"\s+")
pub_data.columns = [
    "index",
    "scale_factor",
    "redshift",
    "time_Gyr",
    "lookback_time_Gyr",
    "time_width_Myr",
]
pub_snaps = np.array(pub_data["index"])


In [12]:
pub_snaps

array([ 20,  23,  26,  29,  33,  37,  41,  46,  52,  59,  67,  77,  88,
       102, 120, 142, 172, 214, 277, 294, 312, 332, 356, 382, 412, 446,
       486, 534, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600])